#!/usr/bin/env bash

set -uo pipefail

ROOT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
VERSIONS_FILE="$ROOT_DIR/home/.chezmoidata/versions.yaml"
CHECKSUMS_FILE="$ROOT_DIR/home/.chezmoidata/checksums.yaml"
CONFIG_TEMPLATE="$ROOT_DIR/home/.chezmoi.yaml.tmpl"
EXTERNALS_TEMPLATE="$ROOT_DIR/home/.chezmoiexternal.yaml.tmpl"
export GH_PAGER=cat

repos=(
  "romkatv/powerlevel10k"
  "zsh-users/zsh-autosuggestions"
  "zsh-users/zsh-syntax-highlighting"
  "MichaelAquilina/zsh-you-should-use"

  "junegunn/vim-plug"

  ##############################################################
  # Default versioned repositories
  "dandavison/delta"
  "sharkdp/bat"
  "sharkdp/fd"
  "junegunn/fzf"
  "direnv/direnv"
  "BurntSushi/ripgrep"
  "lsd-rs/lsd"
  "muesli/duf"
  "FiloSottile/age"
  "tldr-pages/tlrc"
  "fatedier/frp"
  "jqlang/jq"
  "mikefarah/yq"
  "dundee/gdu"
  "kibaamor/ipgeo"
  "kevwan/tproxy"
  "orf/gping"
  "mr-karan/doggo"
  "nxtrace/NTrace-core"
  "bcicen/ctop"
  "kubecolor/kubecolor"
  "alexellis/arkade"
  "upx/upx"
  "koalaman/shellcheck"
  "kibaamor/ipstream"

  ##############################################################
  # Extra binary repositories
  "kubeshark/kubeshark"
  "txn2/kubefwd"

  ##############################################################
  # Arkade-managed binary repositories
  "FiloSottile/mkcert"
  "wagoodman/dive"
  "jesseduffield/lazydocker"
  "kubernetes/minikube"
  "kubernetes-sigs/kind"
  "ahmetb/kubectx"
  "derailed/k9s"
  "helm/helm"
)

commit_repos=(
  "ohmyzsh/ohmyzsh master ohmyzsh"
  "fdellwing/zsh-bat master zshbat"
  "kibaamor/vimconf main vimconf"
  "hugsy/gef main gef"
  "junegunn/fzf-git.sh main fzfgitsh"
)

targets=(
  linux/amd64
  linux/arm64
  darwin/amd64
  darwin/arm64
  windows/amd64
)

SKIP_VERSIONS=0
MAX_JOBS=8

while getopts "sj:h" opt; do
  case "$opt" in
    s) SKIP_VERSIONS=1 ;;
    j) MAX_JOBS="$OPTARG" ;;
    h)
      cat >&2 <<'USAGE'
Usage: ./update-version.sh [-s] [-j N]

Options:
  -s                    Skip GitHub API calls; reuse existing versions.yaml on disk.
  -j N                  Max concurrent checksum downloads (default: 8).
  -h                    Show this help message.
USAGE
      exit 0
      ;;
    *)
      echo "usage: ./update-version.sh [-s] [-j N] [-h]" >&2
      exit 1
      ;;
  esac
done
shift $((OPTIND - 1))

if [[ ! "$MAX_JOBS" =~ ^[1-9][0-9]*$ ]]; then
  echo "error: -j must be a positive integer: $MAX_JOBS" >&2
  exit 1
fi

require_command() {
  if ! command -v "$1" >/dev/null 2>&1; then
    echo "error: required command not found: $1" >&2
    exit 1
  fi
}

load_existing_versions() {
  # shellcheck disable=SC2178
  local -n _ev="$1"
  # shellcheck disable=SC2178
  local -n _ec="$2"
  local key line value
  local section=""

  [[ -f "$VERSIONS_FILE" ]] || return

  # The files are generated by this script, so a lightweight parser is enough
  # and avoids adding a YAML dependency just to read simple top-level maps.
  while IFS= read -r line; do
    case "$line" in
    "versions:")
      section="versions"
      ;;
    "commits:")
      section="commits"
      ;;
    "  "*": "*)
      key="${line%%:*}"
      key="${key#"${key%%[![:space:]]*}"}"
      value="${line#*: }"
      case "$section" in
      versions)
        _ev["$key"]="$value"
        ;;
      commits)
        _ec["$key"]="$value"
        ;;
      esac
      ;;
    esac
  done <"$VERSIONS_FILE"
}

load_existing_checksums() {
  # shellcheck disable=SC2178
  local -n _ec="$1"
  local key line value

  [[ -f "$CHECKSUMS_FILE" ]] || return

  while IFS= read -r line; do
    [[ "$line" == '  "'*'": "'*'"' ]] || continue
    key="${line#  \"}"
    key="${key%%\": \"*}"
    value="${line##*\": \"}"
    value="${value%\"}"
    _ec["$key"]="$value"
  done <"$CHECKSUMS_FILE"
}

assoc_arrays_equal() {
  # shellcheck disable=SC2178
  local -n _existing="$1"
  # shellcheck disable=SC2178
  local -n _updated="$2"
  local key
  for key in "${!_existing[@]}"; do
    [[ "${_updated[$key]:-}" == "${_existing[$key]}" ]] || return 1
  done
  for key in "${!_updated[@]}"; do
    [[ -n "${_existing[$key]+x}" ]] || return 1
  done
  return 0
}

latest_version_for() {
  local repo="$1"
  local version
  version="$(
    { gh release view --repo "$repo" --json tagName --jq '.tagName' 2>/dev/null \
      || gh api --jq '.[0].name // empty' "repos/$repo/tags" 2>/dev/null; } \
      | sed -nE 's/^[^0-9]*([0-9]+([.][0-9]+)*)$/\1/p'
  )" || version=""
  [[ "$version" =~ ^[0-9]+([.][0-9]+)*$ ]] || version=""
  echo "$version"
}

latest_commit_for() {
  local repo="$1"
  local ref="$2"

  gh api \
    --method GET \
    --header 'Accept: application/vnd.github+json' \
    --jq '.sha' \
    "https://api.github.com/repos/$repo/commits/$ref"
}

version_key_for() {
  echo "$1" | cut -d '/' -f 2 | tr -d '-'
}

report_change() {
  local label="$1" key="$2" new_val="$3"
  local map_name="$4"
  local -n map_ref="$map_name"
  local old_val="${map_ref[$key]:-}"
  if [[ -n "${map_ref[$key]+x}" && "$old_val" == "$new_val" ]]; then
    echo "$label unchanged ($new_val)"
  else
    echo "$label updated (${old_val:-none} -> $new_val)"
  fi
}

update_versions() {
  # shellcheck disable=SC2178
  local -n _ev="$1"
  # shellcheck disable=SC2178
  local -n _ec="$2"
  # shellcheck disable=SC2178
  local -n _uv="$3"
  # shellcheck disable=SC2178
  local -n _uc="$4"
  local repo ref key version commit spec

  for repo in "${repos[@]}"; do
    printf 'processing repo: %s ... ' "$repo"
    key="$(version_key_for "$repo")"
    version="$(latest_version_for "$repo")"
    if [[ -z "$version" ]]; then
      echo "failed"
      echo "error: failed to resolve version for $repo" >&2
      exit 1
    fi
    report_change "version" "$key" "$version" _ev
    _uv["$key"]="$version"
  done

  for spec in "${commit_repos[@]}"; do
    read -r repo ref key <<<"$spec"
    printf 'processing repo commit: %s ... ' "$repo"
    commit="$(latest_commit_for "$repo" "$ref")"
    if [[ ! "$commit" =~ ^[0-9a-f]{40}$ ]]; then
      echo "failed"
      echo "error: failed to resolve commit for $repo" >&2
      exit 1
    fi
    report_change "commit" "$key" "$commit" _ec
    _uc["$key"]="$commit"
  done
}

write_versions_file() {
  local output_file="$1"
  # shellcheck disable=SC2178
  local -n _uv="$2"
  # shellcheck disable=SC2178
  local -n _uc="$3"
  local key repo spec

  {
    echo "# Auto-generated by ./update-version.sh — DO NOT EDIT"
    echo "# Generated at: $(date -u +"%Y-%m-%dT%H:%M:%SZ")"
    echo
    echo "versions:"
  } >"$output_file"

  for repo in "${repos[@]}"; do
    key="$(version_key_for "$repo")"
    {
      echo "  # https://github.com/$repo"
      echo "  $key: ${_uv[$key]}"
    } >>"$output_file"
  done

  echo >>"$output_file"
  echo "commits:" >>"$output_file"

  for spec in "${commit_repos[@]}"; do
    read -r repo _ key <<<"$spec"
    {
      echo "  # https://github.com/$repo"
      echo "  $key: ${_uc[$key]}"
    } >>"$output_file"
  done
}

write_json_object() {
  local map_name="$1"
  local key sep=""
  local -n map_ref="$map_name"

  printf '{'
  for key in "${!map_ref[@]}"; do
    printf '%s"%s":"%s"' "$sep" "$key" "${map_ref[$key]}"
    sep=","
  done
  printf '}'
}

render_override_data() {
  local os="$1" arch="$2"
  local versions_name="$3"
  local commits_name="$4"
  local checksums_name="$5"

  printf '{"chezmoi":{"os":"%s","arch":"%s"},"versions":' "$os" "$arch"
  write_json_object "$versions_name"
  printf ',"commits":'
  write_json_object "$commits_name"
  printf ',"checksums":'
  write_json_object "$checksums_name"
  printf '}'
}

canonical_key_for_url() {
  local url="$1"

  url="${url#https://}"
  url="${url#cdn.gh-proxy.org/https://}"
  echo "$url"
}

render_target_urls() {
  local target="$1"
  local versions_array_name="$2"
  local commits_array_name="$3"
  local checksums_array_name="$4"
  local out_file="$5"
  local arch os rendered_file target_data target_config

  os="${target%/*}"
  arch="${target#*/}"
  target_data="$(render_override_data "$os" "$arch" "$versions_array_name" "$commits_array_name" "$checksums_array_name")"

  local chezmoi_env=(env DOTFILES_EXTRA_BINS=1 DOTFILES_ARKADE_BINS=1 DOTFILES_MIRROR=)
  target_config="$("${chezmoi_env[@]}" chezmoi --source "$ROOT_DIR" execute-template \
    --override-data "$target_data" \
    --file "$CONFIG_TEMPLATE")"

rendered_file="$("${chezmoi_env[@]}" chezmoi --source "$ROOT_DIR" \
    --config <(printf '%s\n' "$target_config") \
    --config-format yaml \
    execute-template \
    --override-data "$target_data" \
    --file "$EXTERNALS_TEMPLATE")"

  sed -n -e 's/^[[:space:]]*url:[[:space:]]*"\(.*\)"[[:space:]]*$/\1/p' \
         -e 's/^[[:space:]]*-[[:space:]]*"\(.*\)"[[:space:]]*$/\1/p' \
    <<<"$rendered_file" \
    | sort -u >>"$out_file"
}

add_rendered_urls() {
  local versions_array_name="$1"
  local commits_array_name="$2"
  local checksums_array_name="$3"
  local urls_array_name="$4"
  local pid target url
  local pids=()
  local -n urls_ref="$urls_array_name"

  local tmp_dir=""
  tmp_dir="$(mktemp -d "$ROOT_DIR/.update-version-render.XXXXXX")"

  for target in "${targets[@]}"; do
    render_target_urls "$target" "$versions_array_name" "$commits_array_name" "$checksums_array_name" "$tmp_dir/${target//\//-}" &
    pids+=("$!")
  done

  for pid in "${pids[@]}"; do
    wait "$pid" || { rm -rf "$tmp_dir"; return 1; }
  done

  while IFS= read -r url; do
    [[ -n "$url" ]] || continue
    # shellcheck disable=SC2034
    urls_ref["$url"]=1
  done < <(cat "$tmp_dir"/* 2>/dev/null | sort -u)
  rm -rf "$tmp_dir"
}

update_checksums() {
  # shellcheck disable=SC2178
  local -n _ec="$1"
  # shellcheck disable=SC2178
  local -n _uv="$2"
  # shellcheck disable=SC2178
  local -n _uc="$3"
  # shellcheck disable=SC2178
  local -n _ucs="$4"
  local key url
  local -A seen_keys=()
  local -A urls=()
  local sorted_urls=()

  add_rendered_urls _uv _uc _ec urls

  if ((${#urls[@]} == 0)); then
    _ucs=()
    return
  fi

  mapfile -t sorted_urls < <(printf '%s\n' "${!urls[@]}" | sort)

  local tmp_dir pids=() idx=0
  tmp_dir="$(mktemp -d "$ROOT_DIR/.update-version-checksums.XXXXXX")"

  for url in "${sorted_urls[@]}"; do
    key="$(canonical_key_for_url "$url")"
    if [[ -n "${seen_keys[$key]+x}" ]]; then
      continue
    fi
    seen_keys["$key"]=1
    local cache_val="${_ec[$key]:-}"

    (
      if [[ -n "$cache_val" ]]; then
        echo "cached checksum: $url" >&2
        printf '%s|%s\n' "$key" "$cache_val" >"$tmp_dir/$idx"
      else
        echo "checksumming: $url" >&2
        if sha256="$(curl --fail --silent --show-error --location --retry 3 "$url" | sha256sum | awk '{print $1}')" && [[ -n "$sha256" ]]; then
          printf '%s|%s\n' "$key" "$sha256" >"$tmp_dir/$idx"
        else
          echo "error: failed to checksum URL: $url" >&2
          printf '%s|FAIL\n' "$key" >"$tmp_dir/$idx"
        fi
      fi
    ) &
    pids+=("$!")
    ((idx++))

    while (( ${#pids[@]} >= MAX_JOBS )); do
      wait "${pids[0]}" || true
      pids=("${pids[@]:1}")
    done
  done

  for pid in "${pids[@]}"; do
    wait "$pid" || true
  done

  while IFS='|' read -r key sha256; do
    [[ "$sha256" == "FAIL" ]] && continue
    _ucs["$key"]="$sha256"
  done < <(cat "$tmp_dir"/* 2>/dev/null)

  rm -rf "$tmp_dir"
}

write_checksums_file() {
  local output_file="$1"
  # shellcheck disable=SC2178
  local -n _ucs="$2"
  local key

  {
    echo "# Auto-generated by ./update-version.sh — DO NOT EDIT"
    echo "# Generated at: $(date -u +"%Y-%m-%dT%H:%M:%SZ")"
    echo
    if ((${#_ucs[@]} == 0)); then
      echo "checksums: {}"
      return
    fi
    echo "checksums:"
  } >"$output_file"

  while IFS= read -r key; do
    printf '  "%s": "%s"\n' "$key" "${_ucs[$key]}"
  done < <(printf '%s\n' "${!_ucs[@]}" | sort) >>"$output_file"
}

main() {
  require_command chezmoi
  require_command curl
  require_command gh
  require_command sha256sum

  # shellcheck disable=SC2034
  declare -A UPDATED_COMMITS=()
  # shellcheck disable=SC2034
  declare -A UPDATED_VERSIONS=()

  if [[ "$SKIP_VERSIONS" -eq 1 ]]; then
    load_existing_versions UPDATED_VERSIONS UPDATED_COMMITS
  else
    # shellcheck disable=SC2034
    declare -A EXISTING_COMMITS=()
    # shellcheck disable=SC2034
    declare -A EXISTING_VERSIONS=()

    load_existing_versions EXISTING_VERSIONS EXISTING_COMMITS

    update_versions EXISTING_VERSIONS EXISTING_COMMITS UPDATED_VERSIONS UPDATED_COMMITS

    if assoc_arrays_equal EXISTING_VERSIONS UPDATED_VERSIONS && assoc_arrays_equal EXISTING_COMMITS UPDATED_COMMITS; then
      echo "versions unchanged, skipping write: $VERSIONS_FILE" >&2
    else
      write_versions_file "$VERSIONS_FILE" UPDATED_VERSIONS UPDATED_COMMITS
    fi
  fi

  # shellcheck disable=SC2034
  declare -A EXISTING_CHECKSUMS=()
  # shellcheck disable=SC2034
  declare -A UPDATED_CHECKSUMS=()

  load_existing_checksums EXISTING_CHECKSUMS

  update_checksums EXISTING_CHECKSUMS UPDATED_VERSIONS UPDATED_COMMITS UPDATED_CHECKSUMS

  if assoc_arrays_equal EXISTING_CHECKSUMS UPDATED_CHECKSUMS; then
    echo "checksums unchanged, skipping write: $CHECKSUMS_FILE" >&2
  else
    write_checksums_file "$CHECKSUMS_FILE" UPDATED_CHECKSUMS
  fi
}

main
