#!/usr/bin/env bash

set -euo pipefail

ROOT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
VERSIONS_FILE="$ROOT_DIR/home/.chezmoidata/versions.yaml"
CHECKSUMS_FILE="$ROOT_DIR/home/.chezmoidata/checksums.yaml"
CONFIG_TEMPLATE="$ROOT_DIR/home/.chezmoi.yaml.tmpl"
EXTERNALS_TEMPLATE="$ROOT_DIR/home/.chezmoiexternal.yaml.tmpl"
JOBS="${UPDATE_VERSION_JOBS:-8}"
UPDATE_VERSION_TEMP_DIR=""

declare -A EXISTING_CHECKSUMS=()
declare -A EXISTING_COMMITS=()
declare -A EXISTING_VERSIONS=()
# UPDATED_* are populated completely in memory before any output files are
# generated, so a failed network call cannot leave partially-written YAML.
declare -A UPDATED_CHECKSUMS=()
declare -A UPDATED_COMMITS=()
declare -A UPDATED_VERSIONS=()

export GH_PAGER=cat

repos=(
  "romkatv/powerlevel10k"
  "zsh-users/zsh-autosuggestions"
  "zsh-users/zsh-syntax-highlighting"
  "MichaelAquilina/zsh-you-should-use"

  "junegunn/vim-plug"

  ##############################################################
  # Default versioned repositories
  "dandavison/delta"
  "sharkdp/bat"
  "sharkdp/fd"
  "junegunn/fzf"
  "direnv/direnv"
  "BurntSushi/ripgrep"
  "lsd-rs/lsd"
  "muesli/duf"
  "FiloSottile/age"
  "tldr-pages/tlrc"
  "fatedier/frp"
  "jqlang/jq"
  "mikefarah/yq"
  "dundee/gdu"
  "kibaamor/ipgeo"
  "kevwan/tproxy"
  "orf/gping"
  "mr-karan/doggo"
  "nxtrace/NTrace-core"
  "bcicen/ctop"
  "kubecolor/kubecolor"
  "alexellis/arkade"
  "upx/upx"
  "koalaman/shellcheck"
  "kibaamor/ipstream"

  ##############################################################
  # Extra binary repositories
  "kubeshark/kubeshark"
  "txn2/kubefwd"

  ##############################################################
  # Arkade-managed binary repositories
  "FiloSottile/mkcert"
  "wagoodman/dive"
  "jesseduffield/lazydocker"
  "kubernetes/minikube"
  "kubernetes-sigs/kind"
  "ahmetb/kubectx"
  "derailed/k9s"
  "helm/helm"
)

commit_repos=(
  "ohmyzsh/ohmyzsh master ohmyzsh"
  "fdellwing/zsh-bat master zshbat"
  "kibaamor/vimconf main vimconf"
  "hugsy/gef main gef"
  "junegunn/fzf-git.sh main fzfgitsh"
)

targets=(
  linux/amd64
  linux/arm64
  darwin/amd64
  darwin/arm64
  windows/amd64
)

SKIP_VERSIONS=0
SKIP_CHECKSUMS=0

while [[ $# -gt 0 ]]; do
  case "$1" in
    --skip-versions) SKIP_VERSIONS=1 ;;
    --skip-checksums) SKIP_CHECKSUMS=1 ;;
    -h|--help)
      cat >&2 <<'USAGE'
Usage: ./update-version.sh [--skip-versions] [--skip-checksums]

Options:
  --skip-versions    Skip GitHub API calls; reuse existing versions.yaml on disk.
  --skip-checksums   Skip binary downloads; reuse existing checksums.yaml on disk.
  -h, --help         Show this help message.
USAGE
      exit 0
      ;;
    *)
      echo "error: unknown option: $1" >&2
      echo "usage: ./update-version.sh [--skip-versions] [--skip-checksums] [-h]" >&2
      exit 1
      ;;
  esac
  shift
done

require_command() {
  if ! command -v "$1" >/dev/null 2>&1; then
    echo "error: required command not found: $1" >&2
    exit 1
  fi
}

load_existing_versions() {
  local key
  local line
  local section=""
  local value

  [[ -f "$VERSIONS_FILE" ]] || return

  # The files are generated by this script, so a lightweight parser is enough
  # and avoids adding a YAML dependency just to read simple top-level maps.
  while IFS= read -r line; do
    case "$line" in
    "versions:")
      section="versions"
      ;;
    "commits:")
      section="commits"
      ;;
    "  "*": "*)
      key="${line%%:*}"
      key="${key#"${key%%[![:space:]]*}"}"
      value="${line#*: }"
      case "$section" in
      versions)
        EXISTING_VERSIONS["$key"]="$value"
        ;;
      commits)
        EXISTING_COMMITS["$key"]="$value"
        ;;
      esac
      ;;
    esac
  done <"$VERSIONS_FILE"
}

load_existing_checksums() {
  local key
  local line
  local value

  [[ -f "$CHECKSUMS_FILE" ]] || return

  while IFS= read -r line; do
    [[ "$line" == '  "'*'": "'*'"' ]] || continue
    key="${line#  \"}"
    key="${key%%\": \"*}"
    value="${line##*\": \"}"
    value="${value%\"}"
    EXISTING_CHECKSUMS["$key"]="$value"
  done <"$CHECKSUMS_FILE"
}

normalize_version() {
  sed -nE 's/^[^0-9]*([0-9]+([.][0-9]+)*)$/\1/p'
}

copy_assoc_array() {
  # shellcheck disable=SC2178
  local -n src="$1" dst="$2"
  local key
  for key in "${!src[@]}"; do
    dst["$key"]="${src[$key]}"
  done
}

fill_missing_keys() {
  # shellcheck disable=SC2178
  local -n src="$1" dst="$2"
  local key
  for key in "${!src[@]}"; do
    [[ -n "${dst[$key]+x}" ]] || dst["$key"]="${src[$key]}"
  done
}

latest_version_for() {
  local repo="$1"
  local version
  version="$(
    { gh release view --repo "$repo" --json tagName --jq '.tagName' 2>/dev/null \
      || gh api --jq '.[0].name // empty' "repos/$repo/tags" 2>/dev/null; } \
      | normalize_version
  )" || version=""
  [[ "$version" =~ ^[0-9]+([.][0-9]+)*$ ]] || version=""
  echo "$version"
}

latest_commit_for() {
  local repo="$1"
  local ref="$2"

  gh api \
    --method GET \
    --header 'Accept: application/vnd.github+json' \
    --jq '.sha' \
    "https://api.github.com/repos/$repo/commits/$ref"
}

version_key_for() {
  echo "$1" | cut -d '/' -f 2 | tr -d '-'
}

report_change() {
  local label="$1" key="$2" new_val="$3"
  local old_val="${4:-}"
  local map_name="$5"
  local -n map_ref="$map_name"
  if [[ -n "${map_ref[$key]+x}" && "$old_val" == "$new_val" ]]; then
    echo "$label unchanged ($new_val)"
  else
    echo "$label updated (${old_val:-none} -> $new_val)"
  fi
}

update_versions() {
  local repo ref key version commit spec

  for repo in "${repos[@]}"; do
    printf 'processing repo: %s ... ' "$repo"
    key="$(version_key_for "$repo")"
    version="$(latest_version_for "$repo")"
    if [[ -z "$version" ]]; then
      echo "failed"
      echo "error: failed to resolve version for $repo" >&2
      exit 1
    fi
    report_change "version" "$key" "$version" "${EXISTING_VERSIONS[$key]:-}" EXISTING_VERSIONS
    UPDATED_VERSIONS["$key"]="$version"
  done

  for spec in "${commit_repos[@]}"; do
    read -r repo ref key <<<"$spec"
    printf 'processing repo commit: %s ... ' "$repo"
    commit="$(latest_commit_for "$repo" "$ref")"
    if [[ ! "$commit" =~ ^[0-9a-f]{40}$ ]]; then
      echo "failed"
      echo "error: failed to resolve commit for $repo" >&2
      exit 1
    fi
    report_change "commit" "$key" "$commit" "${EXISTING_COMMITS[$key]:-}" EXISTING_COMMITS
    UPDATED_COMMITS["$key"]="$commit"
  done
}

write_versions_file() {
  local output_file="$1"
  local repo
  local ref
  local key
  local spec

  {
    echo "# Auto-generated by ./update-version.sh — DO NOT EDIT"
    echo "# Generated at: $(date -u +"%Y-%m-%dT%H:%M:%SZ")"
    echo
    echo "versions:"
  } >"$output_file"

  for repo in "${repos[@]}"; do
    key="$(version_key_for "$repo")"
    {
      echo "  # https://github.com/$repo"
      echo "  $key: ${UPDATED_VERSIONS[$key]}"
    } >>"$output_file"
  done

  echo >>"$output_file"
  echo "commits:" >>"$output_file"

  for spec in "${commit_repos[@]}"; do
    read -r repo ref key <<<"$spec"
    {
      echo "  # https://github.com/$repo"
      echo "  $key: ${UPDATED_COMMITS[$key]}"
    } >>"$output_file"
  done
}

# Strip the "Generated at:" header line and compare content-only equality.
yaml_content_eq() {
  local a="$1" b="$2"
  [[ -f "$a" && -f "$b" ]] || return 1
  diff <(sed '/^# Generated at:/d' "$a") <(sed '/^# Generated at:/d' "$b") >/dev/null 2>&1
}

safe_mv_if_changed() {
  local src_file="$1" dst_file="$2"
  if yaml_content_eq "$src_file" "$dst_file"; then
    echo "content unchanged, skipping write: $dst_file" >&2
    rm -f "$src_file"
  else
    mv "$src_file" "$dst_file"
  fi
}

write_json_object() {
  local map_name="$1"
  local first=1
  local key
  local -n map_ref="$map_name"

  printf '{'
  for key in "${!map_ref[@]}"; do
    if [[ "$first" -eq 0 ]]; then
      printf ','
    fi
    first=0
    printf '"%s":"%s"' "$key" "${map_ref[$key]}"
  done
  printf '}'
}

render_override_data() {
  local os="$1"
  local arch="$2"
  local versions_name="$3"
  local commits_name="$4"

  # chezmoi merges multiple override data sources in surprising ways, so pass
  # target data plus the in-memory version/commit maps as a single JSON object.
  printf '{"chezmoi":{"os":"%s","arch":"%s","fqdnHostname":"update-version"},"versions":' "$os" "$arch"
  write_json_object "$versions_name"
  printf ',"commits":'
  write_json_object "$commits_name"
  printf '}'
}

extract_urls() {
  sed -n -e 's/^[[:space:]]*url:[[:space:]]*"\(.*\)"[[:space:]]*$/\1/p' \
         -e 's/^[[:space:]]*-[[:space:]]*"\(.*\)"[[:space:]]*$/\1/p' \
    | sort -u
}

canonical_key_for_url() {
  local url="$1"

  url="${url#https://}"
  url="${url#cdn.gh-proxy.org/https://}"
  echo "$url"
}

render_target_urls() {
  local target="$1"
  local versions_array_name="$2"
  local commits_array_name="$3"
  local out_file="$4"
  local arch os rendered_file target_data target_config

  os="${target%/*}"
  arch="${target#*/}"
  target_data="$(render_override_data "$os" "$arch" "$versions_array_name" "$commits_array_name")"

  local chezmoi_env=(env DOTFILES_EXTRA_BINS=1 DOTFILES_ARKADE_BINS=1 DOTFILES_MIRROR=)
  target_config="$("${chezmoi_env[@]}" chezmoi --source "$ROOT_DIR" execute-template \
    --override-data "$target_data" \
    --file "$CONFIG_TEMPLATE")"

  rendered_file="$("${chezmoi_env[@]}" chezmoi --source "$ROOT_DIR" \
    --config <(printf '%s\n' "$target_config") \
    --config-format yaml \
    execute-template \
    --override-data "$target_data" \
    --file "$EXTERNALS_TEMPLATE" 2>/dev/null || true)"

  extract_urls <<<"$rendered_file" >>"$out_file"
}

add_rendered_urls() {
  local versions_array_name="$1"
  local commits_array_name="$2"
  local urls_array_name="$3"
  local keys_array_name="${4:-}"
  local key
  local pid
  local pids=()
  local target
  local url
  local -n urls_ref="$urls_array_name"

  local tmp_dir=""
  tmp_dir="$(mktemp -d "$ROOT_DIR/.update-version-render.XXXXXX")"

  for target in "${targets[@]}"; do
    render_target_urls "$target" "$versions_array_name" "$commits_array_name" \
      "$tmp_dir/${target//\//-}" &
    pids+=("$!")
  done

  for pid in "${pids[@]}"; do
    wait "$pid" || { rm -rf "$tmp_dir"; return 1; }
  done

  if [[ -n "$keys_array_name" ]]; then
    local -n keys_ref="$keys_array_name"
  fi

  while IFS= read -r url; do
    [[ -n "$url" ]] || continue
    # shellcheck disable=SC2034
    urls_ref["$url"]=1
    if [[ -n "$keys_array_name" ]]; then
      key="$(canonical_key_for_url "$url")"
      # shellcheck disable=SC2034
      keys_ref["$key"]=1
    fi
  done < <(cat "$tmp_dir"/* 2>/dev/null | sort -u)
  rm -rf "$tmp_dir"
}

write_checksum() {
  local url="$1"
  local reuse_existing="${2:-0}"
  local key
  local sha256

  key="$(canonical_key_for_url "$url")"

  # A checksum is reusable only when the same canonical URL was rendered from
  # both the old and updated version maps. Historical checksum entries alone
  # are not enough, because they may refer to versions no longer requested.
  if [[ "$reuse_existing" -eq 1 && -n "${EXISTING_CHECKSUMS[$key]+x}" ]]; then
    echo "cached checksum: $url" >&2
    printf '  "%s": "%s"\n' "$key" "${EXISTING_CHECKSUMS[$key]}"
    return
  fi

  echo "checksumming: $url" >&2
  if ! sha256="$(curl --fail --silent --show-error --location --retry 3 "$url" | sha256sum | awk '{print $1}')"; then
    echo "error: failed to checksum URL: $url" >&2
    return 1
  fi
  printf '  "%s": "%s"\n' "$key" "$sha256"
}

checksum_output_for_urls() {
  local urls_array_name="$1"
  local reusable_keys_array_name="$2"
  local failed=0
  local key
  local pid
  local pids=()
  local reuse_existing
  local sorted_urls=()
  local url
  local -A seen_keys=()
  # shellcheck disable=SC2178
  local -n urls_ref="$urls_array_name"
  local -n reusable_keys_ref="$reusable_keys_array_name"

  mapfile -t sorted_urls < <(printf '%s\n' "${!urls_ref[@]}" | sort)

  {
    for url in "${sorted_urls[@]}"; do
      key="$(canonical_key_for_url "$url")"
      if [[ -n "${seen_keys[$key]+x}" ]]; then
        continue
      fi
      seen_keys["$key"]=1
      reuse_existing=0
      if [[ -n "${reusable_keys_ref[$key]+x}" ]]; then
        reuse_existing=1
      fi

      write_checksum "$url" "$reuse_existing" &
      pids+=("$!")

      # Track only checksum worker PIDs. wait -n can observe unrelated process
      # substitutions in this script and turn successful runs into false
      # failures, so each batch waits for the exact workers it started.
      if [[ "${#pids[@]}" -ge "$JOBS" ]]; then
        for pid in "${pids[@]}"; do
          if ! wait "$pid"; then
            failed=1
          fi
        done
        pids=()
      fi
    done

    for pid in "${pids[@]}"; do
      if ! wait "$pid"; then
        failed=1
      fi
    done

    if [[ "$failed" -ne 0 ]]; then
      echo "error: failed to checksum one or more URLs" >&2
      exit 1
    fi
  } | sort
}

versions_unchanged() {
  local key
  for key in "${!EXISTING_VERSIONS[@]}"; do
    [[ "${UPDATED_VERSIONS[$key]:-}" == "${EXISTING_VERSIONS[$key]}" ]] || return 1
  done
  for key in "${!EXISTING_COMMITS[@]}"; do
    [[ "${UPDATED_COMMITS[$key]:-}" == "${EXISTING_COMMITS[$key]}" ]] || return 1
  done
  return 0
}

update_checksums() {
  local key
  local checksum_output
  local line
  local value

  # shellcheck disable=SC2034
  local -A old_commits=()
  # shellcheck disable=SC2034
  local -A old_keys=()
  # shellcheck disable=SC2034
  local -A old_urls=()
  # shellcheck disable=SC2034
  local -A old_versions=()
  local -A urls=()

  # Render old and updated external URL sets. Their key intersection determines
  # which existing checksums can be reused without downloading the asset again.
  if [[ -f "$VERSIONS_FILE" ]]; then
    if versions_unchanged; then
      # All versions match existing — every checksum in EXISTING_CHECKSUMS is
      # reusable without rendering the old URL set.
      for key in "${!EXISTING_CHECKSUMS[@]}"; do
        # shellcheck disable=SC2034
        old_keys["$key"]=1
      done
    else
      copy_assoc_array EXISTING_VERSIONS old_versions
      copy_assoc_array EXISTING_COMMITS old_commits
      fill_missing_keys UPDATED_VERSIONS old_versions
      fill_missing_keys UPDATED_COMMITS old_commits

      add_rendered_urls old_versions old_commits old_urls old_keys
    fi
  fi

  add_rendered_urls UPDATED_VERSIONS UPDATED_COMMITS urls

  if ((${#urls[@]} == 0)); then
    return
  fi

  if ! checksum_output="$(checksum_output_for_urls urls old_keys)"; then
    return 1
  fi

  while IFS= read -r line; do
    [[ "$line" == '  "'*'": "'*'"' ]] || continue
    key="${line#  \"}"
    key="${key%%\": \"*}"
    value="${line##*\": \"}"
    value="${value%\"}"
    UPDATED_CHECKSUMS["$key"]="$value"
  done <<<"$checksum_output"
}

write_checksums_file() {
  local output_file="$1"
  local key

  {
    echo "# Auto-generated by ./update-version.sh — DO NOT EDIT"
    echo "# Generated at: $(date -u +"%Y-%m-%dT%H:%M:%SZ")"
    echo
    echo "checksums:"
  } >"$output_file"
  if ((${#UPDATED_CHECKSUMS[@]} == 0)); then
    return
  fi

  while IFS= read -r key; do
    printf '  "%s": "%s"\n' "$key" "${UPDATED_CHECKSUMS[$key]}"
  done < <(printf '%s\n' "${!UPDATED_CHECKSUMS[@]}" | sort) >>"$output_file"
}

cleanup_temp_dir() {
  if [[ -n "$UPDATE_VERSION_TEMP_DIR" ]]; then
    rm -rf "$UPDATE_VERSION_TEMP_DIR"
  fi
}

main() {
  local temp_checksums_file
  local temp_versions_file

  if [[ ! "$JOBS" =~ ^[1-9][0-9]*$ ]]; then
    echo "error: UPDATE_VERSION_JOBS must be a positive integer: $JOBS" >&2
    exit 1
  fi

  require_command chezmoi
  require_command curl
  require_command gh
  require_command sha256sum

  load_existing_versions
  load_existing_checksums

  if [[ "$SKIP_VERSIONS" -eq 1 && "$SKIP_CHECKSUMS" -eq 1 && (! -f "$VERSIONS_FILE" || ! -f "$CHECKSUMS_FILE") ]]; then
    echo "error: --skip-versions and --skip-checksums both set, but the required files do not both exist" >&2
    exit 1
  fi

  if [[ "$SKIP_VERSIONS" -eq 1 ]]; then
    copy_assoc_array EXISTING_VERSIONS UPDATED_VERSIONS
    copy_assoc_array EXISTING_COMMITS UPDATED_COMMITS
  else
    update_versions
  fi

  if [[ "$SKIP_CHECKSUMS" -eq 1 ]]; then
    copy_assoc_array EXISTING_CHECKSUMS UPDATED_CHECKSUMS
  else
    update_checksums
  fi

  UPDATE_VERSION_TEMP_DIR="$(mktemp -d "$ROOT_DIR/.update-version.XXXXXX")"
  trap cleanup_temp_dir EXIT

  if [[ "$SKIP_VERSIONS" -eq 0 ]]; then
    temp_versions_file="$UPDATE_VERSION_TEMP_DIR/versions.yaml"
    write_versions_file "$temp_versions_file"
    safe_mv_if_changed "$temp_versions_file" "$VERSIONS_FILE"
  fi

  if [[ "$SKIP_CHECKSUMS" -eq 0 ]]; then
    temp_checksums_file="$UPDATE_VERSION_TEMP_DIR/checksums.yaml"
    write_checksums_file "$temp_checksums_file"
    safe_mv_if_changed "$temp_checksums_file" "$CHECKSUMS_FILE"
  fi

  cleanup_temp_dir
  UPDATE_VERSION_TEMP_DIR=""
  trap - EXIT
}

main
