set -g base-index         1
set -g display-panes-time 10000
set -g mouse              on
set -g pane-base-index    1
set -g renumber-windows   on

setw -g allow-rename      off
setw -g automatic-rename  off
setw -g mode-keys         vi

bind-key X confirm-before -p "Kill session #S? (y/n)" kill-session

setenv -g TMUX_PLUGIN_MANAGER_PATH '~/.tmux/plugins'

set -g @plugin 'seebi/tmux-colors-solarized'
set -g @plugin 'tmux-plugins/tmux-pain-control'
set -g @plugin 'tmux-plugins/tmux-prefix-highlight'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tpm'

# tmux-resurrect
set -g @resurrect-dir '~/.tmux/resurrect'

# tmux-prefix-highlight
set -g status-right '#{prefix_highlight} #H | %a %Y-%m-%d %H:%M'
set -g @prefix_highlight_show_copy_mode 'on'
set -g @prefix_highlight_copy_mode_attr 'fg=white,bg=blue'

run '~/.tmux/plugins/tpm/tpm'
