name: Build and Push DevContainers

on:
  schedule:
    - cron: "0 2 * * 1"
  push:
    paths:
      - ".devcontainer/**"
      - ".github/workflows/devcontainers.yml"
      - "home/**"
  workflow_dispatch:

jobs:
  build-and-push-devcontainers:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        config:
          - base
          - golang

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push DevContainer (${{ matrix.config }})
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/${{ github.repository_owner }}/dotfiles-${{ matrix.config }}
          imageTag: latest
          configFile: .devcontainer/${{ matrix.config }}/devcontainer.json
          push: always
          noCache: true
